#!/bin/bash
while true; do
  CHOICE=$(whiptail --nocancel --title "Odysseyn1x" --menu "Choose and option" 16 40 5 \
    "1" "Checkra1n"   \
    "2" "Odysseyra1n"  \
    "3" "Shut down" \
    "4" "Reboot" \
    "5" "Exit" 3>&1 1>&2 2>&3)
  case $CHOICE in
    1)
      clear
      /usr/bin/checkra1n
      ;;
    2)
      clear
      echo 'Connect an iDevice to this computer.'
      read -p 'Press enter to continue'
      cd /root/
      /usr/bin/odysseyra1n
      echo 'Open Sileo, do all the updates and install libhooker package.'
      echo 'Then reboot manually, and re-jailbreak.'
      read -p 'Press enter to quit'
      ;;
    3)
      /usr/sbin/shutdown now
      ;;
    4)
      /usr/sbin/reboot
      ;;
    5)
      clear
      break
      ;;
  esac
done
