#!/bin/bash
whiptail --nocancel --title "Odysseyn1x" --menu "Choose and option" 16 40 4 \
        "1" "Checkra1n"   \
        "2" "Odysseyra1n"  \
        "3" "Change the keyboard layout" \
        "4" "Shut down" \
        "5" "Reboot" \

case $CHOICE in
  "1")
    /usr/bin/checkra1n
    ;;
  "2")
    cd /root/
    /usr/bin/odysseyra1n
    ;;
  "3")
    /usr/sbin/shutdown now
    ;;
  "4")
    /usr/sbin/reboot
    ;;
 esac
 
