#!/bin/bash
clear
cd /root/android-sandcastle/
/usr/bin/checkra1n -cp > pongo_shell.log 2>&1 &
echo 'Please put your device into DFU'
sleep 1
while true; do
  grep "Booting..." pongo_shell.log > /dev/null 2>&1
  if [[ $? -eq 0 ]]; then
    echo 'Pongo loaded. Give it a second'
    sleep 2
    break
  fi
  sleep 1
done
sleep 5
echo 'Starting Android...'
./load-linux Android.lzma dtbpack
killall checkra1n
read -p 'Press enter to quit'
