#!/bin/bash
# Set colors variables
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;36m'
YELLOW='\033[0;33m'
PURPLE='\033[0;35m'
NC='\033[0m'
BOLD='\033[1;37m'

whatstep() {
  echo -e "${BLUE}${message}...${NC}"
}

successful() {
  echo -e "${GREEN}Done ${message,}.${NC}\n"
}

failed() {
  {
    killall iproxy
    killall checkra1n
  }  > /dev/null 2>&1
  message_uncapitalised="${message,}"
  echo -e "${RED}Failed to ${message_uncapitalised//ing/}.${NC}"
  read -rp 'Press enter to quit'
  exit 1
}

android_logo() {
  echo -e "${GREEN}              #           #${NC}"
  echo -e "${GREEN}               ###########${NC}"
  echo -e "${GREEN}            ###  #######  ###${NC}"
  echo -e "${GREEN}           ###################${NC}"
  echo ''
  echo -e "${GREEN}     ####  ################### ####${NC}"
  echo -e "${GREEN}     ####  ################### ####${NC}"
  echo -e "${GREEN}     ####  ################### ####${NC}"
  echo -e "${GREEN}     ####  ################### ####${NC}"
  echo -e "${GREEN}     ####  ################### ####${NC}"
  echo -e "${GREEN}           ###################${NC}"
  echo -e "${GREEN}           ###################${NC}"
  echo -e "${GREEN}              ####     ####${NC}"
  echo -e "${GREEN}              ####     ####${NC}"
  echo -e "${GREEN}              ####     ####${NC}"
  echo ''
}

linux_logo() {
  echo -e "${YELLOW}                @@@@@@@@@@${NC}"
  echo -e "${YELLOW}               %@@@@@@@@@@@${NC}"
  echo -e "${YELLOW}               @ @ @ .@ @@@${NC}"
  echo -e "${YELLOW}               /@,,,,,,*@@@${NC}"
  echo -e "${YELLOW}               @%.*.*..*@@@@${NC}"
  echo -e "${YELLOW}              @@         @@@@${NC}"
  echo -e "${YELLOW}            @@@           @@@@@${NC}"
  echo -e "${YELLOW}          ,@@@             *@@@@@${NC}"
  echo -e "${YELLOW}         @@@@               ,@@@@@${NC}"
  echo -e "${YELLOW}         @@@@               @@@@@@${NC}"
  echo -e "${YELLOW}        *,,*@.            ,,@@@@**${NC}"
  echo -e "${YELLOW}     *,,,,,,,*@@          *,,,,,,,,${NC}"
  echo -e "${YELLOW}     ,,,,,,,,,,/          ,,,,,,,,..*${NC}"
  echo -e "${YELLOW}    ,....,,,,,,,,@@, (@@@,,,,...../${NC}"
  echo -e "${YELLOW}          *,....*        *.....${NC}"
  echo ''
}

odysseyn1x_logo() {
  echo '  ___   __| |_   _ ___ ___  ___ _   _ _ __ / |_  __'
  echo ' / _ \ / _` | | | / __/ __|/ _ \ | | | `_ \| \ \/ /'
  echo '| (_) | (_| | |_| \__ \__ \  __/ |_| | | | | |>  < '
  echo ' \___/ \__,_|\__, |___/___/\___|\__, |_| |_|_/_/\_\'
  echo '             |___/              |___/              '
}

odysseyra1n_logo() {
  echo -e "${PURPLE}  ___   __| |_   _ ___ ___  ___ _   _ _ __ __ _/ |_ __  ${NC}"
  echo -e "${PURPLE} / _ \ / _\` | | | / __/ __|/ _ \ | | | '__/ _\` | | '_ \ ${NC}"
  echo -e "${PURPLE}| (_) | (_| | |_| \__ \__ \  __/ |_| | | | (_| | | | | |${NC}"
  echo -e "${PURPLE} \___/ \__,_|\__, |___/___/\___|\__, |_|  \__,_|_|_| |_|${NC}"
  echo -e "${PURPLE}             |___/              |___/                   ${NC}"
  echo ''
}

ssh_logo() {
  echo '         _     '
  echo ' ___ ___| |__  '
  echo "/ __/ __| '_ \ "
  echo '\__ \__ \ | | |'
  echo '|___/___/_| |_|'
  echo ''

}