#!/bin/bash
export NEWT_COLORS='root=,black border=white,black window=white,black title=white,black textbox=white,black listbox=white,black'

CHOICE=$(whiptail --cancel-button "Back" --title "Project Sandcastle" --menu "" 13 40 3 \
  "1" "Setup Android" \
  "2" "Start Android" \
  "3" "Start Linux" 3>&1 1>&2 2>&3)
case $CHOICE in
  1)
    /usr/bin/setup_android-sandcastle
    ;;
  2)
    /usr/bin/start_android-sandcastle
    ;;
  3)
    /usr/bin/start_linux-sandcastle
    ;;
esac
