#!/bin/bash
clear
# Load functions and variables
source /usr/bin/common
cd /root/android-sandcastle/

# Show ASCII art
android_logo

/usr/bin/checkra1n -cp > pongo_shell.log 2>&1 &
echo 'Please put your device into DFU mode'
sleep 1
while true; do
  if grep 'Booting...' pongo_shell.log > /dev/null 2>&1; then
    echo 'Pongo loaded. Give it a second'
    sleep 2
    break
  fi
  sleep 1
done
sleep 5
message='Starting Android'
whatstep
if /usr/bin/load-linux Android.lzma dtbpack; then
  successful
  killall checkra1n
  read -p 'Press enter to quit'
else
  failed
fi
