#!/bin/sh
# Load functions and variables
. /usr/bin/common
cd /root/linux-sandcastle/

# Show ASCII art
linux_logo

/usr/bin/checkra1n -cp > pongo_shell.log 2>&1 &
echo 'Please put your device into DFU mode'
sleep 1
while true; do
  if grep 'Booting...' pongo_shell.log > /dev/null 2>&1; then
    echo 'Pongo loaded. Give it a second'
    sleep 2
    break
  fi
  sleep 1
done
sleep 5
message='Starting Linux'
whatstep
if /usr/bin/load-linux Linux.lzma dtbpack; then
  successful
  killall checkra1n
  read -rp 'Press enter to quit' null
else
  failed
fi
