#!/bin/sh
# Load functions and variables
. /usr/bin/common
cd /root/android-sandcastle/

# Show ASCII art
android_logo

CHECKRA1N="$(CHECKRA1N_LOG_PATH=pongo_shell.log /usr/bin/checkra1n -cp)"
echo 'Please put your device into DFU mode'
sleep 1
while true; do
  if grep -q 'Booting...' pongo_shell.log; then
    echo 'Pongo loaded. Give it a second'
    sleep 2
    break
  fi
  sleep 1
done
sleep 5
blue_echo 'Starting Android...'
if /usr/bin/load-linux Android.lzma dtbpack; then
  green_echo 'Done starting Android.'
else
  red_echo 'Failed to start Android.'
fi
enter_to_quit
kill "$CHECKRA1N"
